export const LOGIN_FACEBOOK = 'LOGIN_FACEBOOK';
export const LOGIN_FACEBOOK_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_FACEBOOK_FAILURE = 'LOGIN_USER_FAILURE';
export const LOGOUT_USER = 'LOGOUT_USER';

export const CREATE_EVENT_SUCCESS = 'CREATE_EVENT_SUCCESS';
export const FETCH_EVENTS_SUCCESS = 'FETCH_EVENT_SUCCESS';
export const FETCH_EVENTS = 'FETCH_EVENTS';
export const CREATE_EVENT = 'CREATE_EVENT';
